# settings.yaml
vm:
  - name: "controlplane"
    ip: "192.168.201.10"
    memory: 1024
    cpus: 1
  - name: "node01"
    ip: "192.168.201.11"
    memory: 1024
    cpus: 1
  - name: "node02"
    ip: "192.168.201.12"
    memory: 1024
    cpus: 1